//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cb_digital_news
    {
        public int PaperID { get; set; }
        public string IssueID { get; set; }
        public int PageID { get; set; }
        public string PrimersTitle { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Author { get; set; }
        public string Source { get; set; }
        public string Coordinate { get; set; }
        public string Content { get; set; }
        public string HtmlContent { get; set; }
        public Nullable<int> TransferFlag { get; set; }
        public string PageSNO { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> font { get; set; }
        public string catalog { get; set; }
        public string ArticleName { get; set; }
        public string ArticleNO { get; set; }
        public string PageCount { get; set; }
        public string PageSort { get; set; }
        public string ArticleSort { get; set; }
        public string Editor { get; set; }
        public string PageIndex { get; set; }
        public string PageColumn { get; set; }
        public string ImageName { get; set; }
        public string ImageWaterMark { get; set; }
        public string ImageMark { get; set; }
        public string ReprintTag { get; set; }
        public string ImageFilePath { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string fromWhere { get; set; }
        public string PageName { get; set; }
        public int id { get; set; }
        public string PageStyle { get; set; }
        public string ArticleType { get; set; }
        public string Abstract { get; set; }
    }
}
