//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLEntities : DbContext
    {
        public DLEntities()
            : base("name=DLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cb_digital_news> cb_digital_news { get; set; }
        public virtual DbSet<cb_digital_page> cb_digital_page { get; set; }
        public virtual DbSet<cb_digital_paper> cb_digital_paper { get; set; }
    }
}
